# Generated by Django 4.0.5 on 2022-07-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCiongo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagg',
            name='name',
            field=models.CharField(max_length=100, verbose_name='taggs'),
        ),
    ]
