# Generated by Django 4.0.5 on 2022-07-14 09:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCiongo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puslapis',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, max_length=20000, null=True),
        ),
    ]
