# Generated by Django 4.0.5 on 2022-07-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCiongo', '0002_alter_tagg_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagg',
            name='name',
            field=models.CharField(max_length=100, verbose_name='tagg'),
        ),
        migrations.AlterField(
            model_name='titulinispuslapis',
            name='tagas',
            field=models.ManyToManyField(related_name='posts', to='CCiongo.tagg'),
        ),
    ]
