# Generated by Django 4.0.5 on 2022-07-14 10:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('CCiongo', '0003_alter_puslapis_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puslapis',
            name='content',
            field=tinymce.models.HTMLField(blank=True, max_length=20000, null=True),
        ),
    ]
