# Generated by Django 4.0.5 on 2022-07-05 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CCiongo', '0004_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulinispuslapis',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='CCiongo.author'),
        ),
    ]
