# Generated by Django 4.0.5 on 2022-07-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCiongo', '0007_rename_titulinispuslapis_puslapis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puslapis',
            old_name='tagas',
            new_name='tag',
        ),
    ]
