# Generated by Django 4.0.5 on 2022-07-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCiongo', '0008_rename_tagas_puslapis_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puslapis',
            name='content',
            field=models.TextField(max_length=20000),
        ),
    ]
