# Generated by Django 4.0.5 on 2022-07-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciongo_posts', '0003_tag_delete_tagg_alter_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='tag'),
        ),
    ]
