# Generated by Django 4.0.5 on 2022-07-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciongo_posts', '0004_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploads'),
        ),
    ]
